/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package breakingbank;

import javax.swing.JOptionPane;

/**
 *
 * @author Jesus Centurión
 * @author Fabrizio Falcón
 * @author Santino Gianninoto
 * @author Benjamn Ojeda
 */
public class Deposito extends javax.swing.JFrame {
    
    private final CuentaService cuentaService = new CuentaService();
    private final AuthService authService = new AuthService();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Deposito.class.getName());

    /**
     * Creates new form Deposito
     */
    
    public Deposito() {
        initComponents();
        setLocationRelativeTo(null); // Centrar ventana
        
        // --- AGREGAR ESTO ---
        // Mensaje flotante (amarillo) al pasar el mouse
        jTextField3.setToolTipText("Ingrese el monto solo con números enteros (sin puntos ni comas)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Realizar Depósito");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jButton2.setText("Confirmar Depósito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setText("Monto a depositar:");

        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jButton3.setText("Atrás");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                     
    String textoMonto = jTextField3.getText().trim();

        // 1. Validar si está vacío
        if (textoMonto.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, ingrese un monto.",
                    "Monto vacío",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Validar que sea "netamente numérico" (Sin puntos ni comas)
        if (!esSoloNumeros(textoMonto)) {
            JOptionPane.showMessageDialog(this,
                    "El monto debe contener solo números enteros.\n" +
                    "Por favor, no utilice puntos (.) ni comas (,).",
                    "Formato Incorrecto",
                    JOptionPane.WARNING_MESSAGE);
            // Limpiamos el campo para evitar confusiones
            jTextField3.setText("");
            return;
        }

        // Convertimos a número
        double monto = Double.parseDouble(textoMonto);

        // 3. Validar que sea mayor a cero
        if (monto <= 0) {
            JOptionPane.showMessageDialog(this,
                    "El monto a depositar debe ser mayor que cero.",
                    "Monto inválido",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 4. Validar Límite de 5.000.000
        if (monto > 5000000) {
            JOptionPane.showMessageDialog(this,
                    "El límite máximo por operación es de 5.000.000.\n" +
                    "Por favor, ingrese un monto menor.",
                    "Límite Excedido",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- SI PASA TODO LO ANTERIOR, PROCEDEMOS ---

        String pinIngresado = JOptionPane.showInputDialog(
        this,
        "Ingrese su PIN de transacción:",
        "Validación requerida",
        JOptionPane.PLAIN_MESSAGE
);

// Si canceló
if (pinIngresado == null) {
    return;
}

// 2) Obtener el pin real del usuario logueado
Usuario usuario = authService.getUsuarioActual();
if (usuario == null) {
    JOptionPane.showMessageDialog(this,
        "No hay ningún usuario logueado.",
        "Error",
        JOptionPane.ERROR_MESSAGE);
    return;
}
String pinReal = usuario.getPinTransaccion();

// 3) Validar
if (!pinIngresado.equals(pinReal)) {
    JOptionPane.showMessageDialog(
            this,
            "PIN incorrecto. Operación cancelada.",
            "Error",
            JOptionPane.ERROR_MESSAGE
    );
    return;
}

// 4) PIN correcto → recién ahora se hace el depósito
boolean ok = cuentaService.depositar(monto);

if (!ok) {
    JOptionPane.showMessageDialog(
            this,
            "Ocurrió un error al realizar el depósito.",
            "Error",
            JOptionPane.ERROR_MESSAGE
    );
} else {
    JOptionPane.showMessageDialog(
            this,
            "Depósito realizado con éxito.\nMonto acreditado: " + monto,
            "Depósito Exitoso",
            JOptionPane.INFORMATION_MESSAGE
    );

    new Menu().setVisible(true);
    this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Deposito().setVisible(true));
    }
    
    // Método auxiliar para validar que el texto sea SOLO números (sin puntos ni comas)
    private boolean esSoloNumeros(String texto) {
        return texto.matches("[0-9]+");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
