/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package breakingbank;

import javax.swing.JOptionPane;

/**
 *
 * @author tino
 */
public class Transferencia extends javax.swing.JFrame {
    
    private final CuentaService cuentaService = new CuentaService();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Transferencia.class.getName());

    public Transferencia() {
        initComponents();
        // Agrega esto para centrar la ventana al abrirse
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Realizar Transferencia");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setText("Cédula destinatario:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setText("Monto:");

        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N

        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jButton2.setText("Confirmar Transferencia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jButton3.setText("Atrás");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botónAtrásTransferencia(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String cedulaDestino = jTextField2.getText().trim();
        String textoMonto = jTextField3.getText().trim();

        // --- VALIDACIONES DE FORMATO ---

        // 1. Campos vacíos
        if (cedulaDestino.isEmpty() || textoMonto.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, complete la Cédula de destino y el Monto.",
                    "Datos incompletos",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Solo números (Ni puntos, ni comas, ni letras)
        if (!esSoloNumeros(cedulaDestino) || !esSoloNumeros(textoMonto)) {
            JOptionPane.showMessageDialog(this,
                    "Los campos deben contener solamente números enteros.\n" +
                    "No utilice puntos ni letras.",
                    "Formato Incorrecto",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        double monto = Double.parseDouble(textoMonto);

        // 3. Monto positivo
        if (monto <= 0) {
            JOptionPane.showMessageDialog(this,
                    "El monto a transferir debe ser mayor a cero.",
                    "Monto inválido",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- VALIDACIÓN DE FONDOS (Saldo suficiente) ---
        
        // Validación de saldo
        Usuario usuarioActual = AuthService.getUsuarioActual();
        if (usuarioActual == null) {
        JOptionPane.showMessageDialog(this,
        "No hay ningún usuario logueado.",
        "Error",
        JOptionPane.ERROR_MESSAGE);
        return;
        }
        double saldoActual = usuarioActual.getSaldo();
        if (monto > saldoActual) {
        JOptionPane.showMessageDialog(this,
                "No tiene fondos suficientes.\nSaldo: Gs. " + String.format("%,.0f", saldoActual),
                "Saldo insuficiente",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

        // --- CONFIRMACIÓN FINAL ---
        
        int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Desea transferir Gs. " + String.format("%,.0f", monto) +
            " a la cuenta con Cédula Nro: " + cedulaDestino + "?",
            "Confirmar Transferencia",
            JOptionPane.YES_NO_OPTION);

    if (respuesta != JOptionPane.YES_OPTION) return;

    // --- Ventana emergente OTP ---
    String otpIngresado = JOptionPane.showInputDialog(this,
            "Ingrese su OTP (PIN de transacción):",
            "Validación de Seguridad",
            JOptionPane.QUESTION_MESSAGE);

    if (otpIngresado == null || otpIngresado.trim().isEmpty()) {
        return; // canceló
    }

    if (!otpIngresado.equals(usuarioActual.getPinTransaccion())) {
        JOptionPane.showMessageDialog(this,
                "PIN INCORRECTO. Transferencia cancelada.",
                "Error de Seguridad",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // --- Transferencia ---
    boolean exito = cuentaService.transferir(usuarioActual.getCedula(), cedulaDestino, monto);

    if (exito) {
        JOptionPane.showMessageDialog(this,
                "¡Transferencia realizada exitosamente!",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
        new Menu().setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this,
                "No se pudo completar la transferencia.\nVerifique la Cédula de destino.",
                "Error en la operación",
                JOptionPane.ERROR_MESSAGE);
    }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botónAtrásTransferencia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botónAtrásTransferencia
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botónAtrásTransferencia

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Transferencia().setVisible(true));
    }
// 1. Método auxiliar para validar que sean solo números
    private boolean esSoloNumeros(String texto) {
        return texto != null && texto.matches("[0-9]+");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
